version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./:/code
    image: backend-node-1
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
